import { DesignStyle } from '../types.js';

const darkPrecision: DesignStyle = {
    id: 'dark-precision',
    name: 'Dark Precision',
    version: '1.0.0',
    philosophy: {
        summary: 'Built for those who live in dark mode. High-contrast data visualization on dark surfaces with monospace accents and surgical precision. Every pixel serves the data.',
        emotionalIntent: 'Technical mastery, focused intensity, developer confidence',
        functionalContract: 'The interface is a professional instrument for people who think in code. It respects the user\'s expertise and never dumbs things down.',
        bestFor: ['Developer tools', 'IDE extensions', 'CLI dashboards', 'API monitoring', 'Database management', 'DevOps platforms', 'Code review tools'],
        notIdealFor: ['Consumer apps', 'Marketing sites', 'Children\'s platforms', 'Social media', 'Content/editorial sites'],
    },
    colors: {
        primary: { value: '#22D3EE', role: 'primary', usage: 'Primary actions, interactive elements. Cyan for maximum dark-bg visibility.' },
        primaryHover: { value: '#06B6D4', role: 'primary-hover', usage: 'Slightly deeper cyan on hover.' },
        secondary: { value: '#A78BFA', role: 'secondary', usage: 'Secondary highlights. Violet for syntax-highlighting familiarity.' },
        surface: { value: '#1E1E1E', role: 'surface', usage: 'Editor-like surface. VS Code dark inspired.' },
        surfaceAlt: { value: '#252526', role: 'surface-alt', usage: 'Sidebar, panel backgrounds. Subtle elevation.' },
        background: { value: '#121212', role: 'background', usage: 'Deep dark background. Not pure black to avoid OLED smearing.' },
        foreground: { value: '#E4E4E7', role: 'foreground', usage: 'Primary text. Slightly warm white for reduced eye strain.' },
        muted: { value: '#27272A', role: 'muted', usage: 'Subtle dividers, disabled backgrounds.' },
        mutedForeground: { value: '#71717A', role: 'muted-foreground', usage: 'Comments, timestamps, secondary labels.' },
        border: { value: '#3F3F46', role: 'border', usage: 'Panel dividers. Visible but not dominant.' },
        borderHover: { value: '#52525B', role: 'border-hover', usage: 'Brighter on hover for interactive containers.' },
        danger: { value: '#F87171', role: 'danger', usage: 'Errors, failed tests, build failures.' },
        success: { value: '#4ADE80', role: 'success', usage: 'Passed tests, successful deploys, healthy status.' },
        warning: { value: '#FBBF24', role: 'warning', usage: 'Deprecation warnings, slow queries, approaching limits.' },
        info: { value: '#60A5FA', role: 'info', usage: 'Informational, debug output, neutral logs.' },
        overlay: { value: 'rgba(0, 0, 0, 0.7)', role: 'overlay', usage: 'Dark overlay for modals, maintaining immersion.' },
        accent: { value: 'rgba(34, 211, 238, 0.1)', role: 'accent', usage: 'Selected line highlight, active panel indicator.' },
        accentForeground: { value: '#22D3EE', role: 'accent-foreground', usage: 'Text on accent backgrounds.' },
    },
    typography: {
        fonts: {
            heading: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace",
            body: "'Inter', 'SF Pro Text', -apple-system, sans-serif",
            mono: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace",
            rationale: 'Monospace for headings creates immediate developer-tool recognition. Body text uses Inter for readability in longer prose. The mono/sans pairing signals: this is a tool built by developers, for developers.',
        },
        scale: { xs: '0.6875rem', sm: '0.75rem', base: '0.8125rem', lg: '0.875rem', xl: '1rem', '2xl': '1.25rem', '3xl': '1.5rem', '4xl': '2rem', '5xl': '2.5rem' },
        weights: { light: 300, regular: 400, medium: 500, semibold: 600, bold: 700 },
        lineHeights: { tight: '1.3', normal: '1.5', relaxed: '1.6', loose: '1.8' },
        letterSpacing: { tight: '0', normal: '0', wide: '0.1em' },
        rules: [
            'Headings: monospace, medium weight (500) — technical authority without shouting',
            'Body: sans-serif, regular weight, small (13px base) for density',
            'Code/data values: always monospace, always — no exceptions',
            'Labels: uppercase + wide tracking for scanability in dense layouts',
            'Line numbers, timestamps: xs size, muted color',
        ],
    },
    spacing: {
        baseUnit: '4px', baseValue: 4,
        scale: [0, 1, 2, 3, 4, 6, 8, 10, 12, 16, 20, 24, 32, 40, 48],
        allowedMultiples: 'Multiples of 4px. Tight, functional spacing.',
        rules: ['Component padding: 8px-16px — dense but readable', 'Panel gaps: 1px-4px — tight seams between panels', 'Code block padding: 12px-16px', 'Gutter widths: consistent 8px or 12px', 'Dense is beautiful here — wasted space is wasted data'],
    },
    bordersShadows: {
        radius: {
            none: '0px', sm: '2px', md: '4px', lg: '6px', xl: '8px', full: '9999px',
            default: '4px',
            rationale: 'Small radius (4px) is enough to soften without losing technical character. IDE-like elements use 2px or 0px.',
        },
        borderWidth: { none: '0px', thin: '1px', default: '1px', thick: '2px', heavy: '3px' },
        shadows: {
            none: 'none', sm: '0 1px 2px rgba(0,0,0,0.3)', md: '0 2px 8px rgba(0,0,0,0.4)', lg: '0 4px 16px rgba(0,0,0,0.5)', xl: '0 8px 32px rgba(0,0,0,0.6)', inner: 'inset 0 1px 2px rgba(0,0,0,0.3)',
            rationale: 'Shadows are dark and functional. On dark backgrounds, they need higher opacity to be visible.',
        },
        rules: [
            'Borders: 1px in muted color for panel separation',
            'Active/focused elements: primary color border (1-2px)',
            'Selected items: left accent bar (2-3px primary color)',
            'Shadows minimal — use border and background shifts for elevation',
            'Glow effects for primary interactive elements: 0 0 8px primary-at-30%',
        ],
    },
    components: {
        button: { description: 'Compact, technical buttons.', rules: ['Padding: 4px 12px', 'Radius: 4px', 'Border: 1px solid border', 'Small text, medium weight', 'Hover: background lighten', 'Key actions: primary color outline glow'], variants: ['primary', 'secondary', 'ghost', 'danger', 'icon-only'] },
        card: { description: 'Dark panels. Think IDE panels.', rules: ['Border: 1px solid border', 'Radius: 4px', 'Background: surface', 'Padding: 12px-16px', 'Title bar with muted border-bottom'], variants: ['panel', 'terminal', 'code-block', 'metric'] },
        table: { description: 'Dense data grids. Monospace values.', rules: ['Header: uppercase, xs, wide tracking', 'Data: monospace', 'Cell padding: 6px 12px', 'Row borders: 1px muted', 'Hover: accent background', 'Sortable columns: glow indicator'], variants: ['default', 'compact', 'log-view'] },
        navbar: { description: 'Minimal status bar.', rules: ['Height: 40px', 'Background: surface-alt', 'Border-bottom: 1px', 'Status indicators: colored dots', 'Monospace breadcrumbs'], variants: ['default', 'with-status', 'terminal-style'] },
        sidebar: { description: 'File-tree style sidebar.', rules: ['Width: 240px', 'Background: surface-alt', 'Items: small, mono', 'Active: accent bg + primary text', 'Indent: 16px per level', 'Right border: 1px'], variants: ['file-tree', 'nav', 'collapsed'] },
        modal: { description: 'Command-palette style dialog.', rules: ['Radius: 8px', 'Border: 1px border', 'Background: surface', 'Shadow: lg', 'No title bar — search input first', 'Keyboard-navigable list'], variants: ['command-palette', 'dialog', 'confirm'] },
        form: { description: 'Technical form inputs.', rules: ['Labels: xs, uppercase, wide tracking', 'Inputs: 4px radius, surface-alt bg, 1px border', 'Focus: primary border glow', 'Monospace for code/config inputs'], variants: ['settings', 'config', 'inline'] },
        badge: { description: 'Status indicators.', rules: ['Radius: 2px or full for dots', '10% opacity bg', '1px border matching color', 'Uppercase, xs, wide tracking'], variants: ['status', 'count', 'tag', 'severity'] },
        input: { description: 'Terminal-inspired inputs.', rules: ['Background: surface-alt', 'Border: 1px border', 'Radius: 4px', 'Mono font for code inputs', 'Focus: primary border + box glow', 'Prefix: $ or > for terminal-style'], variants: ['text', 'code', 'search', 'terminal'] },
        dropdown: { description: 'Command palette menus.', rules: ['Dark surface bg', '1px border', 'Radius: 6px', 'Items: hover accent bg', 'Keyboard shortcuts shown right-aligned', 'Search input at top'], variants: ['command', 'select', 'filter'] },
        tabs: { description: 'Editor-style tabs.', rules: ['Active: surface bg, bright text', 'Inactive: surface-alt bg, muted text', 'Bottom border active: primary color (2px)', 'Close icon on hover', 'No radius — flat tab style'], variants: ['editor', 'underline', 'segment'] },
        toast: { description: 'Log-style notifications.', rules: ['Background: surface', 'Left border: 3px status color', 'Mono timestamp prefix', 'Compact: single line', 'Auto-dismiss: 3s for info, sticky for errors'], variants: ['info', 'success', 'warning', 'error'] },
    },
    interactions: {
        philosophy: 'Instant. No waiting, no flourishes. Developers value milliseconds. Every interaction should feel like a keyboard shortcut — immediate and precise.',
        transitions: {
            duration: { instant: '0ms', fast: '50ms', normal: '100ms', slow: '150ms', verySlow: '200ms' },
            easing: { default: 'ease-out', in: 'ease-in', out: 'ease-out', inOut: 'ease-in-out', bounce: 'ease-out' },
        },
        hover: { behavior: 'Background brightness shift. Subtle glow for primary actions.', rules: ['Background: lighten 5-8%', 'Interactive: subtle glow in primary color', 'Cursor: pointer for actions, text for inputs', 'No transforms'] },
        focus: { behavior: 'Primary color border + subtle glow.', rules: ['1px primary border', 'Box-shadow: 0 0 0 2px primary-at-20%', 'Visible against dark backgrounds', 'Keyboard focus: always visible'] },
        loading: { pattern: 'Minimal, terminal-inspired.', rules: ['Spinner: thin ring, primary color', 'Progress: thin bar, no radius', 'Skeleton: dark rectangles pulse', 'Text loading: blinking cursor'] },
        animation: { philosophy: 'Nearly zero. Speed is the only animation that matters.', rules: ['Max 150ms for anything', 'Command palette: instant appear', 'Tooltips: instant, no fade', 'Only exception: chart data transitions'] },
    },
    antiPatterns: [
        { name: 'Light Theme Elements', description: 'White backgrounds, light surfaces mixed into the dark UI', why: 'Breaks immersion and causes eye strain. Dark precision is ALL dark.', correction: 'All surfaces use dark palette. No white backgrounds anywhere.' },
        { name: 'Rounded Corners > 8px', description: 'Large border-radius on panels', why: 'Over-rounding makes developer tools feel like consumer apps.', correction: 'Max 6px on panels. 4px default.' },
        { name: 'Decorative Animations', description: 'Bouncing, sliding, fading UI elements', why: 'Developers value speed. Animations are wasted milliseconds.', correction: 'Keep all animations under 100ms. Prefer instant.' },
        { name: 'Sans-serif Headings', description: 'Using sans-serif for section titles in a dev-tool context', why: 'Monospace headings signal "this is a technical tool." Sans-serif headings signal "this is an app."', correction: 'Monospace for headings and data. Sans-serif for body text only.' },
        { name: 'Low Information Density', description: 'Large padding, big text, generous whitespace', why: 'Developers want to see maximum data per viewport. Wasted space means more scrolling.', correction: 'Tight spacing (8-16px). Small text (13px base). Dense layouts.' },
    ],
    componentHierarchies: {
        dashboard: {
            pageType: 'dashboard',
            components: [
                { name: 'status-bar', priority: 1, placement: 'top, 40px height', responsiveBehavior: 'Collapses to icons' },
                { name: 'sidebar', priority: 2, placement: 'left, 240px', responsiveBehavior: 'Hidden, toggle overlay' },
                { name: 'terminal-panel', priority: 3, placement: 'bottom, resizable', responsiveBehavior: 'Full-width, reduced height' },
                { name: 'editor-area', priority: 4, placement: 'center, fills remaining', responsiveBehavior: 'Full-width when sidebar hidden' },
                { name: 'activity-panel', priority: 5, placement: 'right, 300px', responsiveBehavior: 'Hidden, toggle overlay' },
            ],
            layoutRules: ['1px gaps between all panels', 'Resizable panel borders', 'No padding at page level — every pixel used'],
            relationships: ['Status bar shows build/test state', 'Editor is primary focus', 'Terminal provides execution context', 'Activity shows logs/events'],
        },
        landing: {
            pageType: 'landing',
            components: [
                { name: 'terminal-hero', priority: 1, placement: 'top, terminal-styled demo', responsiveBehavior: 'Full-width, reduced height' },
                { name: 'feature-grid', priority: 2, placement: 'dark cards grid', responsiveBehavior: 'Single column' },
                { name: 'code-example', priority: 3, placement: 'syntax-highlighted code block', responsiveBehavior: 'Horizontal scroll' },
                { name: 'cta', priority: 4, placement: 'bottom, command-line style', responsiveBehavior: 'Full-width' },
            ],
            layoutRules: ['Dark throughout — no light sections', 'Section gap: 32px', 'Code examples are interactive if possible'],
            relationships: ['Terminal hero demonstrates the product', 'Features explain capabilities', 'Code example shows integration'],
        },
    },
    compatibleStyles: ['industrial-minimalism'],
    blendingRules: [
        'Dark precision naturally blends with industrial minimalism — shared dark palette and data density',
        'Can adopt industrial minimalism color system while maintaining mono typography',
        'Never blend with light-themed styles — the dark context is non-negotiable',
    ],
};

export default darkPrecision;
