import { DesignStyle } from '../types.js';

const softModernism: DesignStyle = {
    id: 'soft-modernism',
    name: 'Soft Modernism',
    version: '1.0.0',
    philosophy: {
        summary: 'Warm, approachable design using rounded forms, gentle shadows, and muted palettes. The antidote to cold corporate design.',
        emotionalIntent: 'Warm approachability, gentle confidence, human comfort',
        functionalContract: 'The interface feels like a trusted friend — reliable, easy, never intimidating.',
        bestFor: ['Consumer SaaS', 'Health/wellness apps', 'Education platforms', 'Personal finance', 'Team collaboration', 'Mobile-first products'],
        notIdealFor: ['Trading platforms', 'Military UIs', 'Developer tools', 'Data-intensive dashboards', 'Luxury brands'],
    },
    colors: {
        primary: { value: '#7C3AED', role: 'primary', usage: 'Primary actions. Soft violet communicates creativity and warmth.' },
        primaryHover: { value: '#6D28D9', role: 'primary-hover', usage: 'Deeper violet on hover.' },
        secondary: { value: '#F472B6', role: 'secondary', usage: 'Secondary actions. Warm pink adds playful energy.' },
        surface: { value: '#FFFFFF', role: 'surface', usage: 'Card backgrounds.' },
        surfaceAlt: { value: '#FAF5FF', role: 'surface-alt', usage: 'Light purple tint for alternate sections.' },
        background: { value: '#FAFAF9', role: 'background', usage: 'Warm off-white. Avoids sterility of pure white.' },
        foreground: { value: '#1C1917', role: 'foreground', usage: 'Warm near-black (stone-900).' },
        muted: { value: '#F5F5F4', role: 'muted', usage: 'Subtle backgrounds, disabled states.' },
        mutedForeground: { value: '#78716C', role: 'muted-foreground', usage: 'Secondary text. Warm gray.' },
        border: { value: '#E7E5E4', role: 'border', usage: 'Subtle borders. Warm gray that blends.' },
        borderHover: { value: '#D6D3D1', role: 'border-hover', usage: 'Slightly more defined on hover.' },
        danger: { value: '#EF4444', role: 'danger', usage: 'Error states.' },
        success: { value: '#22C55E', role: 'success', usage: 'Success states.' },
        warning: { value: '#F59E0B', role: 'warning', usage: 'Warning states.' },
        info: { value: '#6366F1', role: 'info', usage: 'Informational callouts.' },
        overlay: { value: 'rgba(28, 25, 23, 0.3)', role: 'overlay', usage: 'Light overlay for modals.' },
        accent: { value: '#EDE9FE', role: 'accent', usage: 'Selected states, highlighted areas.' },
        accentForeground: { value: '#5B21B6', role: 'accent-foreground', usage: 'Text on accent backgrounds.' },
    },
    typography: {
        fonts: {
            heading: "'DM Sans', 'Inter', -apple-system, sans-serif",
            body: "'Inter', -apple-system, sans-serif",
            mono: "'JetBrains Mono', monospace",
            rationale: 'DM Sans provides geometric warmth for headings. Inter for clean body text.',
        },
        scale: { xs: '0.75rem', sm: '0.875rem', base: '1rem', lg: '1.125rem', xl: '1.25rem', '2xl': '1.5rem', '3xl': '2rem', '4xl': '2.5rem', '5xl': '3.5rem' },
        weights: { light: 300, regular: 400, medium: 500, semibold: 600, bold: 700 },
        lineHeights: { tight: '1.25', normal: '1.5', relaxed: '1.75', loose: '2' },
        letterSpacing: { tight: '-0.025em', normal: '0', wide: '0.025em' },
        rules: [
            'Headings: semibold (600) with negative letter-spacing',
            'Body: regular (400) with relaxed line-height (1.75)',
            'Never use all-uppercase — it reads as SHOUTING in a soft context',
            'Maximum 3 distinct sizes per screen',
            'Always use font-smoothing: antialiased',
        ],
    },
    spacing: {
        baseUnit: '4px', baseValue: 4,
        scale: [0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 24, 32, 40, 48, 64, 80, 96],
        allowedMultiples: 'Multiples of 4px. Generous spacing reflects warm character.',
        rules: ['Component padding: 20px-28px', 'Element gaps: 12px-16px', 'Section spacing: 48px-80px', 'Always err on the side of more space'],
    },
    bordersShadows: {
        radius: {
            none: '0px', sm: '6px', md: '10px', lg: '14px', xl: '20px', full: '9999px',
            default: '10px',
            rationale: 'Generous rounding (10px+) is the defining visual trait. Rounded corners communicate friendliness and safety.',
        },
        borderWidth: { none: '0px', thin: '1px', default: '1px', thick: '2px', heavy: '2px' },
        shadows: {
            none: 'none', sm: '0 1px 3px rgba(0,0,0,0.04), 0 1px 2px rgba(0,0,0,0.03)', md: '0 4px 6px rgba(0,0,0,0.04), 0 2px 4px rgba(0,0,0,0.03)', lg: '0 10px 15px rgba(0,0,0,0.06), 0 4px 6px rgba(0,0,0,0.03)', xl: '0 20px 25px rgba(0,0,0,0.08), 0 8px 10px rgba(0,0,0,0.04)', inner: 'inset 0 2px 4px rgba(0,0,0,0.03)',
            rationale: 'Extremely soft shadows — barely there. Gentle suggestion of depth.',
        },
        rules: ['Elevation through shadows, not borders', 'Shadows barely perceptible at a glance', 'Minimum 10px radius on containers', 'Buttons: pill shape or 12px+ radius', 'Focus rings: soft glow at 30% primary opacity'],
    },
    components: {
        button: { description: 'Rounded, friendly buttons.', rules: ['Padding: 10px 24px', 'Border-radius: full (pill) or 10px', 'No uppercase text', 'Hover: brightness + subtle shadow', 'Active: scale(0.98)', 'Min height: 40px'], variants: ['primary', 'secondary', 'ghost', 'soft', 'link'] },
        card: { description: 'Soft-cornered cards with gentle elevation.', rules: ['Radius: 14px', 'Shadow: sm or md', 'Padding: 24px', 'Hover: shadow increases subtly'], variants: ['elevated', 'outlined', 'flat', 'interactive'] },
        table: { description: 'Friendly data tables.', rules: ['Container: rounded card', 'Header: surface-alt bg, rounded top', 'Cell padding: 14px 16px', 'Row hover: accent bg'], variants: ['simple', 'rounded', 'compact'] },
        navbar: { description: 'Warm navigation bar.', rules: ['Height: 56px', 'Subtle bottom border', 'Active: primary color or dot indicator'], variants: ['default', 'centered', 'floating'] },
        sidebar: { description: 'Friendly side nav.', rules: ['Width: 256px', 'Nav items: 8px radius', 'Active: accent bg + primary text', 'Section headers: small, muted'], variants: ['persistent', 'with-avatars', 'compact'] },
        modal: { description: 'Rounded, inviting dialog.', rules: ['Radius: 20px', 'Shadow: xl', 'Light overlay', 'Entry: scale + fade animation'], variants: ['default', 'large', 'bottom-sheet'] },
        form: { description: 'Friendly forms.', rules: ['Labels: medium weight, natural case', 'Input radius: 10px', 'Focus: primary ring', 'Group spacing: 24px'], variants: ['stacked', 'contained', 'wizard'] },
        badge: { description: 'Soft rounded badges.', rules: ['Radius: full', 'Pastel background', 'No borders', 'Never uppercase'], variants: ['default', 'dot', 'icon-badge'] },
        input: { description: 'Rounded inputs.', rules: ['Radius: 10px', 'Border: 1px subtle', 'Focus: primary ring', 'Smooth transitions'], variants: ['default', 'filled', 'with-icon', 'textarea'] },
        dropdown: { description: 'Soft dropdown menus.', rules: ['Menu: 12px radius, white, shadow', 'Items: 6px radius hover bg', 'Entry: subtle scale + fade'], variants: ['select', 'combobox', 'multi-select'] },
        tabs: { description: 'Rounded tab navigation.', rules: ['Active: primary bg pill', 'Inactive: muted text', 'Container: muted bg, full radius'], variants: ['pills', 'underline', 'segment'] },
        toast: { description: 'Friendly toasts.', rules: ['Radius: 12px', 'Shadow: lg', 'Rounded status icon', 'No harsh borders'], variants: ['success', 'error', 'info', 'warning'] },
    },
    interactions: {
        philosophy: 'Interactions should feel delightful — like a well-made physical product. Subtle spring animations and smooth state changes.',
        transitions: {
            duration: { instant: '0ms', fast: '120ms', normal: '200ms', slow: '300ms', verySlow: '400ms' },
            easing: { default: 'cubic-bezier(0.4, 0, 0.2, 1)', in: 'cubic-bezier(0.4, 0, 1, 1)', out: 'cubic-bezier(0, 0, 0.2, 1)', inOut: 'cubic-bezier(0.4, 0, 0.2, 1)', bounce: 'cubic-bezier(0.34, 1.56, 0.64, 1)' },
        },
        hover: { behavior: 'Gentle elevation and warmth changes.', rules: ['Cards: shadow increase, translate-y(-2px)', 'Buttons: brightness change', 'Scale: max 1.02'] },
        focus: { behavior: 'Soft focus ring.', rules: ['Box-shadow ring at 30% primary opacity', 'Smooth transition', 'Like a gentle glow'] },
        loading: { pattern: 'Gentle loading states.', rules: ['Skeleton: soft gray pulse', 'Spinners: rounded, primary color', 'Button loading: inline spinner'] },
        animation: { philosophy: 'Natural and joyful — like friendly gestures.', rules: ['Entry: fade + rise at 200ms', 'Modals: scale(0.95→1) + fade at 250ms', 'Micro-interactions: subtle bounce on success', 'Never interrupt user flow'] },
    },
    antiPatterns: [
        { name: 'Sharp Corners', description: 'Border-radius below 6px', why: 'Sharp corners feel cold. Soft modernism is defined by warmth.', correction: 'Minimum 8px. Default 10-14px for containers.' },
        { name: 'Cold Colors', description: 'Pure grays without warm undertones', why: 'Cold colors make the interface impersonal.', correction: 'Use warm neutrals: stone palette instead of gray.' },
        { name: 'Heavy Borders', description: 'Thick, dark borders on containers', why: 'Contradicts lightness and airiness.', correction: '1px light borders, or shadows instead.' },
        { name: 'Uppercase Text', description: 'All-caps for labels or headings', why: 'Reads as aggressive in a soft context.', correction: 'Natural case for everything.' },
        { name: 'Harsh Transitions', description: 'Instant state changes', why: 'Jarring. Breaks comfortable feeling.', correction: 'Minimum 120ms transitions.' },
    ],
    componentHierarchies: {
        dashboard: {
            pageType: 'dashboard',
            components: [
                { name: 'sidebar', priority: 1, placement: 'left, 256px', responsiveBehavior: 'Bottom tab bar on mobile' },
                { name: 'page-header', priority: 2, placement: 'top of content', responsiveBehavior: 'Stacks vertically' },
                { name: 'welcome-card', priority: 3, placement: 'full-width', responsiveBehavior: 'Reduces padding' },
                { name: 'metric-cards', priority: 4, placement: 'grid', responsiveBehavior: '1-col mobile' },
                { name: 'activity-feed', priority: 5, placement: 'below metrics', responsiveBehavior: 'Full-width list' },
            ],
            layoutRules: ['20px grid gap', '32px content padding', 'Max-width: 1100px'],
            relationships: ['Welcome card provides context', 'Metrics summarize data', 'Activity shows recent changes'],
        },
        landing: {
            pageType: 'landing',
            components: [
                { name: 'hero', priority: 1, placement: 'top, centered', responsiveBehavior: 'Smaller heading on mobile' },
                { name: 'features', priority: 2, placement: '3-column cards', responsiveBehavior: 'Single column' },
                { name: 'cta', priority: 3, placement: 'centered, warm bg section', responsiveBehavior: 'Full-width CTA' },
            ],
            layoutRules: ['Section gap: 80px', 'Max-width: 800px text', 'Background sections for visual rhythm'],
            relationships: ['Hero → trust → features → CTA'],
        },
    },
    compatibleStyles: ['clean-utility', 'glassmorphism', 'warm-editorial'],
    blendingRules: [
        'Pairs naturally with warm-editorial typography for content sections',
        'Can adopt clean-utility structural rules while maintaining rounded forms',
        'Glass effects can enhance soft modernism cards for premium feel',
    ],
};

export default softModernism;
