import { DesignStyle } from '../types.js';

const warmEditorial: DesignStyle = {
    id: 'warm-editorial',
    name: 'Warm Editorial',
    version: '1.0.0',
    philosophy: {
        summary: 'Content-forward design inspired by premium editorial publications. Serif typography, generous reading rhythm, and intentional restraint create a reading experience that honors the content.',
        emotionalIntent: 'Intellectual warmth, curated authority, thoughtful craftsmanship',
        functionalContract: 'The interface says: your content matters, and we treat it with the respect it deserves. Typography leads, layout serves, and chrome disappears.',
        bestFor: ['Blog platforms', 'News sites', 'Documentation', 'Content-heavy SaaS', 'Publishing tools', 'Knowledge bases', 'Long-form reading apps'],
        notIdealFor: ['Data dashboards', 'Gaming platforms', 'Developer tools', 'High-density admin panels', 'Real-time monitoring'],
    },
    colors: {
        primary: { value: '#B45309', role: 'primary', usage: 'Primary actions. Warm amber that feels editorial without being corporate blue.' },
        primaryHover: { value: '#92400E', role: 'primary-hover', usage: 'Deeper amber on hover.' },
        secondary: { value: '#0F766E', role: 'secondary', usage: 'Secondary highlights. Teal provides complementary contrast.' },
        surface: { value: '#FFFFFF', role: 'surface', usage: 'Content backgrounds. Pure white for maximum text contrast.' },
        surfaceAlt: { value: '#FFFBEB', role: 'surface-alt', usage: 'Warm cream for alternate sections. Magazine-paper feel.' },
        background: { value: '#FEF3C7', role: 'background', usage: 'Warm cream page background. Reduces eye strain for long reading sessions.' },
        foreground: { value: '#1C1917', role: 'foreground', usage: 'Primary text. Warm near-black for comfortable reading.' },
        muted: { value: '#F5F5F4', role: 'muted', usage: 'Subtle backgrounds.' },
        mutedForeground: { value: '#78716C', role: 'muted-foreground', usage: 'Captions, bylines, metadata.' },
        border: { value: '#E7E5E4', role: 'border', usage: 'Section dividers. Subtle, warm gray.' },
        borderHover: { value: '#D6D3D1', role: 'border-hover', usage: 'Hover state for interactive containers.' },
        danger: { value: '#DC2626', role: 'danger', usage: 'Error states.' },
        success: { value: '#16A34A', role: 'success', usage: 'Success states.' },
        warning: { value: '#D97706', role: 'warning', usage: 'Warning states.' },
        info: { value: '#0891B2', role: 'info', usage: 'Informational callouts.' },
        overlay: { value: 'rgba(28, 25, 23, 0.4)', role: 'overlay', usage: 'Modal overlays.' },
        accent: { value: '#FEF3C7', role: 'accent', usage: 'Highlighted text backgrounds, pullquotes.' },
        accentForeground: { value: '#92400E', role: 'accent-foreground', usage: 'Text on accent backgrounds.' },
    },
    typography: {
        fonts: {
            heading: "'Playfair Display', 'Georgia', 'Times New Roman', serif",
            body: "'Source Serif 4', 'Charter', 'Georgia', serif",
            mono: "'JetBrains Mono', 'Fira Code', monospace",
            rationale: 'Playfair Display brings editorial grandeur to headings. Source Serif 4 provides beautiful reading rhythm for body text. Serif throughout is the defining choice — this is a literary experience.',
        },
        scale: { xs: '0.75rem', sm: '0.875rem', base: '1.125rem', lg: '1.25rem', xl: '1.5rem', '2xl': '2rem', '3xl': '2.5rem', '4xl': '3.5rem', '5xl': '4.5rem' },
        weights: { light: 300, regular: 400, medium: 500, semibold: 600, bold: 700 },
        lineHeights: { tight: '1.2', normal: '1.6', relaxed: '1.8', loose: '2' },
        letterSpacing: { tight: '-0.02em', normal: '0', wide: '0.1em' },
        rules: [
            'Body text base size: 18px (1.125rem) — larger for comfortable reading',
            'Headings: serif, bold, with negative tracking for display sizes',
            'Body: serif, regular weight, generous line-height (1.8) for reading rhythm',
            'Maximum line width: 65-75 characters — the typographic ideal for readability',
            'Pullquotes: large italic serif, centered, generous vertical space',
            'Captions: sans-serif (Inter), small, muted — contrast with serif body',
        ],
    },
    spacing: {
        baseUnit: '4px', baseValue: 4,
        scale: [0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 24, 32, 40, 48, 64, 80, 96, 128],
        allowedMultiples: 'Multiples of 4px. Very generous spacing for reading comfort.',
        rules: ['Paragraph spacing: 1.5em — generous for reading flow', 'Section spacing: 64px-96px — magazine-style section breaks', 'Image margins: 48px vertical, full-bleed or inset', 'Content max-width: 680px — the reading column', 'Sidebar: additional 320px alongside reading column'],
    },
    bordersShadows: {
        radius: {
            none: '0px', sm: '2px', md: '4px', lg: '6px', xl: '8px', full: '9999px',
            default: '2px',
            rationale: 'Minimal rounding. Editorial design uses sharp or barely-rounded elements. The content, not the chrome, carries the warmth.',
        },
        borderWidth: { none: '0px', thin: '1px', default: '1px', thick: '2px', heavy: '3px' },
        shadows: {
            none: 'none', sm: '0 1px 2px rgba(0,0,0,0.05)', md: '0 2px 4px rgba(0,0,0,0.08)', lg: '0 4px 12px rgba(0,0,0,0.1)', xl: '0 8px 24px rgba(0,0,0,0.12)', inner: 'inset 0 1px 2px rgba(0,0,0,0.05)',
            rationale: 'Shadows are used sparingly. Editorial design relies on typography and whitespace, not elevation effects.',
        },
        rules: ['Horizontal rules (hr) as section dividers — 1px, centered, 40% width', 'Borders: subtle, warm gray, used for utility not decoration', 'Image borders: none — images float in white/cream space', 'Blockquote: left border 3px in accent/primary color', 'Drop caps may use decorative borders'],
    },
    components: {
        button: { description: 'Editorial CTA buttons — understated but clear.', rules: ['Padding: 12px 28px', 'Radius: 2px', 'Text: medium weight, natural case', 'Primary: warm amber bg', 'Hover: darken 10%', 'Style: minimal chrome, text-forward'], variants: ['primary', 'secondary', 'link (inline text link)', 'subscribe'] },
        card: { description: 'Article cards with image + text.', rules: ['No visible border or shadow — content defines the card', 'Image: top or left, aspect ratio maintained', 'Title: serif, bold', 'Excerpt: serif, regular, muted', 'Padding: 0 — whitespace does the work'], variants: ['featured (large image)', 'standard (small image + text)', 'text-only', 'horizontal'] },
        table: { description: 'Editorial data tables.', rules: ['Minimal chrome: top/bottom borders on header', 'Cell padding: 12px 16px', 'Serif text for values', 'Caption above table: italic, muted', 'No background colors — typography differentiates'], variants: ['simple', 'statistical', 'comparison'] },
        navbar: { description: 'Magazine-style masthead navigation.', rules: ['Logo: centered or left, editorial typeface', 'Nav items: sans-serif, small, wide tracking, uppercase', 'Bottom border: thin, elegant', 'Height: 64px — generous'], variants: ['classic (centered logo)', 'magazine (logo left, nav right)', 'minimal'] },
        sidebar: { description: 'Editorial sidebar for related content.', rules: ['Width: 320px', 'Content: related articles, tags, author bio', 'Typography: smaller serif', 'Dividers: thin horizontal rules', 'Background: surface-alt or transparent'], variants: ['right-rail', 'sticky-toc (table of contents)', 'related-articles'] },
        modal: { description: 'Clean overlay for subscription/sharing.', rules: ['Radius: 4px', 'Background: white or cream', 'Shadow: lg', 'Typography-forward: headline is the hero', 'Minimal chrome'], variants: ['subscribe', 'share', 'paywall'] },
        form: { description: 'Clean editorial forms.', rules: ['Labels: sans-serif, small, medium weight', 'Inputs: minimal border, 2px radius', 'Focus: primary (amber) border', 'Group spacing: 24px', 'Submit: editorial CTA style'], variants: ['newsletter-signup', 'comment-form', 'contact'] },
        badge: { description: 'Category and tag labels.', rules: ['Sans-serif, xs, uppercase, wide tracking', 'Background: none or very subtle', 'Color: primary or muted', 'Minimal padding'], variants: ['category', 'tag', 'date'] },
        input: { description: 'Minimal editorial inputs.', rules: ['Border-bottom only (underline style) or full subtle border', 'Radius: 0-2px', 'Serif or sans-serif depending on context', 'Focus: amber/primary underline'], variants: ['underline', 'bordered', 'search', 'textarea'] },
        dropdown: { description: 'Clean selection menus.', rules: ['Minimal styling matching inputs', 'Menu: white bg, subtle shadow', 'Items: comfortable padding', 'No heavy borders'], variants: ['select', 'filter'] },
        tabs: { description: 'Section navigation for content types.', rules: ['Active: underline 2px primary', 'Text: sans-serif, small, uppercase tracking', 'Subtle container divider', 'Minimal spacing between tabs'], variants: ['underline', 'text-only'] },
        toast: { description: 'Subtle notifications.', rules: ['Background: surface-alt (cream)', 'Border: 1px subtle', 'Shadow: sm', 'Text: sans-serif, small', 'Position: bottom-center'], variants: ['info', 'success', 'error'] },
    },
    interactions: {
        philosophy: 'Interactions should be invisible. The content is the experience. Chrome and behavior should never compete with reading.',
        transitions: {
            duration: { instant: '0ms', fast: '100ms', normal: '200ms', slow: '300ms', verySlow: '400ms' },
            easing: { default: 'ease-in-out', in: 'ease-in', out: 'ease-out', inOut: 'ease-in-out', bounce: 'ease-out' },
        },
        hover: { behavior: 'Subtle color changes. Never transform content.', rules: ['Links: color change or underline appear', 'Cards: no transform — subtle shadow or opacity', 'Buttons: background darken', 'Never scale or translate text content'] },
        focus: { behavior: 'Understated focus indicator.', rules: ['2px outline in primary color', 'Works on cream/white backgrounds', 'Never disrupts reading flow'] },
        loading: { pattern: 'Minimal, content-shaped loading.', rules: ['Skeleton: gray lines matching text layout', 'Image placeholders: cream rectangles', 'No spinners in content areas'] },
        animation: { philosophy: 'Reading should not be interrupted by motion.', rules: ['No entrance animations on body text', 'Images may fade in on scroll (200ms)', 'Page transitions: simple fade', 'No parallax — it distracts from reading'] },
    },
    antiPatterns: [
        { name: 'Sans-serif Body Text', description: 'Using sans-serif for article/body content', why: 'Serif typography IS this style. Removing it removes the editorial character entirely.', correction: 'Always use serif for body text. Sans-serif only for UI chrome and captions.' },
        { name: 'Narrow Line Width', description: 'Content columns wider than 75 characters', why: 'Long lines cause eye fatigue. Typography research shows 65-75 chars is optimal for reading.', correction: 'Max content width: 680px with 18px base size.' },
        { name: 'Visual Clutter', description: 'Heavy UI chrome, thick borders, prominent shadows around content', why: 'Chrome competes with content. In editorial design, the text IS the interface.', correction: 'Minimize borders and shadows. Use whitespace and typography for hierarchy.' },
        { name: 'Cold Colors', description: 'Blue-gray or cool-toned palette', why: 'Editorial warmth comes from warm tones. Cool colors make content feel corporate or clinical.', correction: 'Use warm neutrals (stone, amber, cream). Warm accent colors.' },
        { name: 'Dense Layouts', description: 'Tight spacing, small text, multiple columns of content', why: 'Reading requires space and rhythm. Dense layouts cause fatigue and reduce comprehension.', correction: 'Generous spacing: 1.8 line-height, 48px+ between sections, single content column.' },
    ],
    componentHierarchies: {
        dashboard: {
            pageType: 'dashboard',
            components: [
                { name: 'masthead', priority: 1, placement: 'top, editorial header', responsiveBehavior: 'Simplified on mobile' },
                { name: 'featured-article', priority: 2, placement: 'hero-sized, top of content', responsiveBehavior: 'Full-width image, stacked text' },
                { name: 'article-grid', priority: 3, placement: 'below featured, 2-3 columns', responsiveBehavior: 'Single column' },
                { name: 'sidebar', priority: 4, placement: 'right rail, 320px', responsiveBehavior: 'Moves below content' },
            ],
            layoutRules: ['Content column: 680px max', 'Sidebar: 320px', 'Section gaps: 64px', 'Article grid gap: 32px'],
            relationships: ['Featured article is the editorial pick', 'Grid shows recent content', 'Sidebar provides supplementary navigation'],
        },
        landing: {
            pageType: 'landing',
            components: [
                { name: 'editorial-hero', priority: 1, placement: 'full-width, large serif heading', responsiveBehavior: 'Reduce heading size' },
                { name: 'value-props', priority: 2, placement: '2-column, text-heavy', responsiveBehavior: 'Single column' },
                { name: 'testimonial', priority: 3, placement: 'centered pullquote style', responsiveBehavior: 'Reduce font size' },
                { name: 'subscribe-cta', priority: 4, placement: 'centered, warm background', responsiveBehavior: 'Full-width' },
            ],
            layoutRules: ['Max-width: 800px text', 'Section gap: 96px', 'Typography-led layout'],
            relationships: ['Hero establishes editorial voice', 'Value props explain', 'Testimonial validates', 'CTA converts'],
        },
    },
    compatibleStyles: ['soft-modernism', 'clean-utility'],
    blendingRules: [
        'Warm editorial typography can enhance soft modernism content sections',
        'Can borrow clean-utility structural patterns while maintaining editorial typography',
        'Never blend with brutalist or industrial styles — the aesthetic languages are incompatible',
    ],
};

export default warmEditorial;
